export const ADD_BOILER = 'ADD_BOILER';
export const ADD_BOILER_SUCCESS = 'ADD_BOILER_SUCCESS';
export const ADD_BOILER_ERROR = 'ADD_BOILER_ERROR';

export const EDIT_BOILER = 'EDIT_BOILER';
export const EDIT_BOILER_SUCCESS = 'EDIT_BOILER_SUCCESS';
export const EDIT_BOILER_ERROR = 'EDIT_BOILER_ERROR';

export const DELETE_BOILER = 'DELETE_BOILER';
export const DELETE_BOILER_SUCCESS = 'DELETE_BOILER_SUCCESS';
export const DELETE_BOILER_ERROR = 'DELETE_BOILER_ERROR';

export const GET_BOILER = 'GET_BOILER';
export const GET_BOILER_SUCCESS = 'GET_BOILER_SUCCESS';
export const GET_BOILER_ERROR = 'GET_BOILER_ERROR';

export const GET_BOILERS = 'GET_BOILERS';
export const GET_BOILERS_SUCCESS = 'GET_BOILERS_SUCCESS';
export const GET_BOILERS_ERROR = 'GET_BOILERS_ERROR';

export const SET_BOILER = 'SET_BOILER';