export const ADD_BUILDING = 'ADD_BUILDING';
export const ADD_BUILDING_SUCCESS = 'ADD_BUILDING_SUCCESS';
export const ADD_BUILDING_ERROR = 'ADD_BUILDING_ERROR';

export const EDIT_BUILDING = 'EDIT_BUILDING';
export const EDIT_BUILDING_SUCCESS = 'EDIT_BUILDING_SUCCESS';
export const EDIT_BUILDING_ERROR = 'EDIT_BUILDING_ERROR';

export const DELETE_BUILDING = 'DELETE_BUILDING';
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS';
export const DELETE_BUILDING_ERROR = 'DELETE_BUILDING_ERROR';
